services:
  angular-portfolio:
    build:
      context: .
      dockerfile: Dockerfile
      # Enable BuildKit for better caching and multi-stage optimization
      args:
        BUILDKIT_INLINE_CACHE: 1
    ports:
      - "8080:80"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
